version: '3.8'
services:
  db:
    build: backend
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  jupyter:
    image: tensorflow/tensorflow:latest-py3-jupyter
    command: jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.allow_origin='https://colab.research.google.com'
    container_name: jupyter
    expose:
      - 5432
    ports:
      - "8888:8888"
    


