version: '3.8'
services:

  db:
    build: backend
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    networks:
      recomienda_network:
        ipv4_address: 172.20.1.2


  # jupyter:
  #   image: tensorflow/tensorflow:latest-py3-jupyter
  #   command: jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.allow_origin='https://colab.research.google.com'
  #   container_name: jupyter
  #   expose:
  #     - 5432
  #   ports:
  #     - 8888:8888
  #   networks:
  #     recomienda_network:
  #       ipv4_address: 172.20.1.3

  api:
    build: API 
    container_name: API
    ports: 
      - "80:80"
    expose:
      - "5432"
    restart: on-failure:15

    networks:
      recomienda_network:
        ipv4_address: 172.20.1.4
    depends_on:
      - "db"
    volumes:
      - E:/Github/app_recomienda/API/app/:/code/app
      - E:/Github/app_recomienda/API/ML_model/:/code/ML_model

networks:
  recomienda_network:
    ipam:
      config:
        - subnet: 172.20.1.0/24
    


